/*
* 需要对内容进行修改，请修改并更新此文件，建议不要修改html文件
*图片建议尺寸分别为：284*160,195*260
* */
//走进春运区块，图片和链接地址
var list1={//走进春运部分
    "name":"走进春运",
    "moreUrl":"http://www.w3school.com.cn&a=more2",//点击更多精彩跳转地址
    "data":[
        {
            "img":"1.1.1.jpg",//图片
            'title':'李玉刚混搭维塔斯合作默契十足',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"1.1.2.jpg",//图片
            'title':'韩国人气天团EXO嗨唱引爆全场',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"1.2.1.jpg",//图片
            'title':'火风霍尊父子档温暖跨年夜',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"1.2.2.jpg",//图片
            'title':'安七炫联手梅葆玖上演创意京剧',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"1.3.1.jpg",//图片
            'title':'火风霍尊父子档温暖跨年夜',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"1.3.2.jpg",//图片
            'title':'安七炫联手梅葆玖上演创意京剧',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        }
    ]
};
var list2={//爆笑电影部分
    "name":"爆笑电影",
    "moreUrl":"http://www.w3school.com.cn&a=more2",//点击更多精彩跳转地址
    "data":[
        {
            "img":"2.1.1.jpg",//图片
            'title':'如果我爱你',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"2.1.2.jpg",//图片
            'title':'爱在春天',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"2.2.1.jpg",//图片
            'title':'借用一下你的爱',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"2.2.2.jpg",//图片
            'title':'爱可以重来',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"2.3.1.jpg",//图片
            'title':'好想好想爱上你',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"2.3.2.jpg",//图片
            'title':'冰与火的青春',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        }
    ]
};
var list3={//热播剧集部分
    "name":"热播剧集",
    "moreUrl":"http://www.w3school.com.cn&a=more2",//点击更多精彩跳转地址
    "data":[
        {
            "img":"3.1.1.jpg",//图片
            'title':'女汉子真爱公式',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"3.1.2.jpg",//图片
            'title':'购物女王',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"3.2.1.jpg",//图片
            'title':'煎饼侠',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"3.2.2.jpg",//图片
            'title':'唐人街探案',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"3.3.1.jpg",//图片
            'title':'致我们终将到来的爱情',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        },
        {
            "img":"3.3.2.jpg",//图片
            'title':'万万没想到',//标题
            "url":"http://www.w3school.com.cn/"//点击跳转链接地址
        }
    ]
};
var rule={//活动规则
    'cont':[//内容
        '1.客户完成登录后，即可参加。。。。。。。。',
        '2.活动期间，单个用户每天都可以。。。。',
        '3.活动期间，单个用户每天都可以。。。。',
        '4.活动期间，单个用户每天都可以。。。。'
    ]
};
var url={
    'activeUrl':'http://wap.gs.10086.cn/migu_data.html',//800M免费领的图标放到右下角
    'returnHomePageUrl':'http://www.w3school.com.cn'//返回首页链接地址
};

